// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _1015bookstore.data.EF;

#nullable disable

namespace _1015bookstore.data.Migrations
{
    [DbContext(typeof(_1015DbContext))]
    [Migration("20231217023556_addproductimage")]
    partial class addproductimage
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("_1015bookstore.data.Entities.AppConfig", b =>
                {
                    b.Property<string>("key")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("key");

                    b.ToTable("AppConfigs", (string)null);

                    b.HasData(
                        new
                        {
                            key = "HomeTitle",
                            value = "This is home page of eShopSolution"
                        },
                        new
                        {
                            key = "Homekeyword",
                            value = "This is keyword of eShopSolution"
                        },
                        new
                        {
                            key = "HomeDescription",
                            value = "This is description of eShopSolution"
                        });
                });

            modelBuilder.Entity("_1015bookstore.data.Entities.Cart", b =>
                {
                    b.Property<int>("product_id")
                        .HasColumnType("int");

                    b.Property<Guid>("user_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("datecreated")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.HasKey("product_id", "user_id");

                    b.HasIndex("user_id");

                    b.ToTable("Carts", (string)null);
                });

            modelBuilder.Entity("_1015bookstore.data.Entities.Category", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int?>("categoryparentid")
                        .HasColumnType("int");

                    b.Property<string>("createdby")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("datecreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateupdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("updatedby")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            id = 1,
                            createdby = "HeThong",
                            datecreated = new DateTime(2023, 12, 17, 9, 35, 55, 841, DateTimeKind.Local).AddTicks(3992),
                            dateupdated = new DateTime(2023, 12, 17, 9, 35, 55, 841, DateTimeKind.Local).AddTicks(4000),
                            name = "Sách giáo khoa",
                            status = 0,
                            updatedby = "HeThong"
                        },
                        new
                        {
                            id = 2,
                            createdby = "HeThong",
                            datecreated = new DateTime(2023, 12, 17, 9, 35, 55, 841, DateTimeKind.Local).AddTicks(4002),
                            dateupdated = new DateTime(2023, 12, 17, 9, 35, 55, 841, DateTimeKind.Local).AddTicks(4003),
                            name = "Sách ngôn ngữ",
                            status = 0,
                            updatedby = "HeThong"
                        },
                        new
                        {
                            id = 3,
                            categoryparentid = 1,
                            createdby = "HeThong",
                            datecreated = new DateTime(2023, 12, 17, 9, 35, 55, 841, DateTimeKind.Local).AddTicks(4004),
                            dateupdated = new DateTime(2023, 12, 17, 9, 35, 55, 841, DateTimeKind.Local).AddTicks(4004),
                            name = "Sách giáo khoa lớp 1",
                            status = 0,
                            updatedby = "HeThong"
                        },
                        new
                        {
                            id = 4,
                            categoryparentid = 2,
                            createdby = "HeThong",
                            datecreated = new DateTime(2023, 12, 17, 9, 35, 55, 841, DateTimeKind.Local).AddTicks(4005),
                            dateupdated = new DateTime(2023, 12, 17, 9, 35, 55, 841, DateTimeKind.Local).AddTicks(4006),
                            name = "Sách tiếng anh",
                            status = 0,
                            updatedby = "HeThong"
                        });
                });

            modelBuilder.Entity("_1015bookstore.data.Entities.Order", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int>("address_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("completedate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("deliverydate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("orderdate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("paymentdate")
                        .HasColumnType("datetime2");

                    b.Property<int>("status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<Guid>("user_id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("id");

                    b.HasIndex("user_id");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("_1015bookstore.data.Entities.OrderDetail", b =>
                {
                    b.Property<int>("product_id")
                        .HasColumnType("int");

                    b.Property<int>("order_id")
                        .HasColumnType("int");

                    b.Property<float>("price")
                        .HasColumnType("real");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.HasKey("product_id", "order_id");

                    b.HasIndex("order_id");

                    b.ToTable("OrderDetails", (string)null);
                });

            modelBuilder.Entity("_1015bookstore.data.Entities.Product", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("alias")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("buy_count")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("createdby")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("datecreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateupdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("flashsale")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("like_count")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("madein")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("mfgdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("nop")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("price")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("quanity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("review_count")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<float>("start_count")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("real")
                        .HasDefaultValue(0f);

                    b.Property<int>("status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("suppiler")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("updatedby")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("view_count")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("waranty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("yop")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            id = 1,
                            alias = "Sach toan lop 1",
                            author = "",
                            brand = "",
                            buy_count = 0,
                            createdby = "HeThong",
                            datecreated = new DateTime(2023, 12, 17, 9, 35, 55, 841, DateTimeKind.Local).AddTicks(4022),
                            dateupdated = new DateTime(2023, 12, 17, 9, 35, 55, 841, DateTimeKind.Local).AddTicks(4023),
                            description = "Đây là sách toán hay dành cho trẻ em",
                            flashsale = false,
                            like_count = 0,
                            madein = "",
                            mfgdate = new DateTime(2023, 12, 17, 9, 35, 55, 841, DateTimeKind.Local).AddTicks(4020),
                            name = "Sách toán lớp 1",
                            nop = "",
                            price = 10000m,
                            quanity = 100,
                            review_count = 0,
                            start_count = 0f,
                            status = 0,
                            suppiler = "",
                            updatedby = "HeThong",
                            view_count = 0,
                            waranty = 30,
                            yop = 2023
                        },
                        new
                        {
                            id = 2,
                            alias = "Sach phat am Mai Lan Huong",
                            author = "",
                            brand = "",
                            buy_count = 0,
                            createdby = "HeThong",
                            datecreated = new DateTime(2023, 12, 17, 9, 35, 55, 841, DateTimeKind.Local).AddTicks(4027),
                            dateupdated = new DateTime(2023, 12, 17, 9, 35, 55, 841, DateTimeKind.Local).AddTicks(4028),
                            description = "Đây là sách oke nè",
                            flashsale = false,
                            like_count = 0,
                            madein = "",
                            mfgdate = new DateTime(2023, 12, 17, 9, 35, 55, 841, DateTimeKind.Local).AddTicks(4026),
                            name = "Sách phát âm Mai Lan Hương",
                            nop = "",
                            price = 10000m,
                            quanity = 100,
                            review_count = 0,
                            start_count = 0f,
                            status = 0,
                            suppiler = "",
                            updatedby = "HeThong",
                            view_count = 0,
                            waranty = 30,
                            yop = 2023
                        });
                });

            modelBuilder.Entity("_1015bookstore.data.Entities.ProductImage", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("caption")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("createdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("imagepath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("is_default")
                        .HasColumnType("bit");

                    b.Property<int>("product_id")
                        .HasColumnType("int");

                    b.Property<long>("sizeimage")
                        .HasColumnType("bigint");

                    b.Property<int>("sortorder")
                        .HasColumnType("int");

                    b.Property<DateTime>("updatedate")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("product_id");

                    b.ToTable("ProductImages", (string)null);
                });

            modelBuilder.Entity("_1015bookstore.data.Entities.ProductInCategory", b =>
                {
                    b.Property<int>("product_id")
                        .HasColumnType("int");

                    b.Property<int>("category_id")
                        .HasColumnType("int");

                    b.HasKey("product_id", "category_id");

                    b.HasIndex("category_id");

                    b.ToTable("ProductInCategory", (string)null);

                    b.HasData(
                        new
                        {
                            product_id = 1,
                            category_id = 3
                        },
                        new
                        {
                            product_id = 2,
                            category_id = 4
                        });
                });

            modelBuilder.Entity("_1015bookstore.data.Entities.PromotionalCode", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("createdby")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("datecreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateupdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("discount_rate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("fromdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<DateTime>("todate")
                        .HasColumnType("datetime2");

                    b.Property<string>("updatedby")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("PromotionalCodes", (string)null);
                });

            modelBuilder.Entity("_1015bookstore.data.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8d04dce2-969a-435d-bba4-df3f325983dc"),
                            ConcurrencyStamp = "c4c93676-ecfb-4403-8296-e64a32889c82",
                            Name = "admin",
                            NormalizedName = "admin",
                            description = "Administrator role"
                        });
                });

            modelBuilder.Entity("_1015bookstore.data.Entities.Transaction", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<decimal>("amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("externaltransactionid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("fee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("provider")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("result")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<DateTime>("transactiondate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("user_id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("id");

                    b.HasIndex("user_id");

                    b.ToTable("Transactions", (string)null);
                });

            modelBuilder.Entity("_1015bookstore.data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dob")
                        .HasColumnType("datetime2");

                    b.Property<string>("firstname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("lastname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("69bd714f-9576-45ba-b5b7-f00649be00de"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a51da11b-29de-473d-85d0-19dd0dcb8501",
                            Email = "21520208@gm.uit.edu.vn",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "21520208@gm.uit.edu.vn",
                            NormalizedUserName = "admin",
                            PasswordHash = "AQAAAAEAACcQAAAAENPtygPKmMXn4MRPwM1PtHnqGxMgI2FLEpyO9EpsXLI9AGKv4yYDBWbDXG7ByvTPag==",
                            PhoneNumber = "0907448146",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "admin",
                            dob = new DateTime(2020, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            firstname = "Nguyen",
                            lastname = "Duy"
                        });
                });

            modelBuilder.Entity("_1015bookstore.data.Entities.UserAddress", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("address_detail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("coordinates_X")
                        .HasColumnType("real");

                    b.Property<float>("coordinates_Y")
                        .HasColumnType("real");

                    b.Property<string>("district")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("is_default")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("receiver_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("receiver_phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sub_district")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("user_id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("id");

                    b.HasIndex("user_id");

                    b.ToTable("UserAddresses", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.ToTable("UserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("69bd714f-9576-45ba-b5b7-f00649be00de"),
                            RoleId = new Guid("8d04dce2-969a-435d-bba4-df3f325983dc")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("_1015bookstore.data.Entities.Cart", b =>
                {
                    b.HasOne("_1015bookstore.data.Entities.Product", "product")
                        .WithMany("carts")
                        .HasForeignKey("product_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_1015bookstore.data.Entities.User", "user")
                        .WithMany("carts")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("product");

                    b.Navigation("user");
                });

            modelBuilder.Entity("_1015bookstore.data.Entities.Order", b =>
                {
                    b.HasOne("_1015bookstore.data.Entities.User", "user")
                        .WithMany("orders")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("_1015bookstore.data.Entities.OrderDetail", b =>
                {
                    b.HasOne("_1015bookstore.data.Entities.Order", "order")
                        .WithMany("orderdetails")
                        .HasForeignKey("order_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_1015bookstore.data.Entities.Product", "product")
                        .WithMany("orderdetails")
                        .HasForeignKey("product_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("order");

                    b.Navigation("product");
                });

            modelBuilder.Entity("_1015bookstore.data.Entities.ProductImage", b =>
                {
                    b.HasOne("_1015bookstore.data.Entities.Product", "product")
                        .WithMany("productimages")
                        .HasForeignKey("product_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("product");
                });

            modelBuilder.Entity("_1015bookstore.data.Entities.ProductInCategory", b =>
                {
                    b.HasOne("_1015bookstore.data.Entities.Category", "category")
                        .WithMany("productincategory")
                        .HasForeignKey("category_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_1015bookstore.data.Entities.Product", "product")
                        .WithMany("productincategory")
                        .HasForeignKey("product_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("category");

                    b.Navigation("product");
                });

            modelBuilder.Entity("_1015bookstore.data.Entities.Transaction", b =>
                {
                    b.HasOne("_1015bookstore.data.Entities.User", "user")
                        .WithMany("transactions")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("_1015bookstore.data.Entities.UserAddress", b =>
                {
                    b.HasOne("_1015bookstore.data.Entities.User", "user")
                        .WithMany("addresses")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("_1015bookstore.data.Entities.Category", b =>
                {
                    b.Navigation("productincategory");
                });

            modelBuilder.Entity("_1015bookstore.data.Entities.Order", b =>
                {
                    b.Navigation("orderdetails");
                });

            modelBuilder.Entity("_1015bookstore.data.Entities.Product", b =>
                {
                    b.Navigation("carts");

                    b.Navigation("orderdetails");

                    b.Navigation("productimages");

                    b.Navigation("productincategory");
                });

            modelBuilder.Entity("_1015bookstore.data.Entities.User", b =>
                {
                    b.Navigation("addresses");

                    b.Navigation("carts");

                    b.Navigation("orders");

                    b.Navigation("transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
