// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _1015bookstore.web.Data;

#nullable disable

namespace _1015bookstore.web.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20231122171018_AddIdentifyAuthentication")]
    partial class AddIdentifyAuthentication
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("_1015bookstore.web.Data.Entity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("_1015bookstore.web.Data.Entity.CartItem", b =>
                {
                    b.Property<int>("product_id")
                        .HasColumnType("int");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.Property<float>("price")
                        .HasColumnType("real");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.HasKey("product_id", "user_id");

                    b.HasIndex("user_id");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("_1015bookstore.web.Data.Entity.Category", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int>("categoryparentid")
                        .HasColumnType("int");

                    b.Property<string>("createdby")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("createdtime")
                        .HasColumnType("datetime2");

                    b.Property<int>("is_status")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("updatedby")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("updatedtime")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("_1015bookstore.web.Data.Entity.Order", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int>("address_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("completedate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("createdtime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("deliverydate")
                        .HasColumnType("datetime2");

                    b.Property<int>("is_status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("paymentdate")
                        .HasColumnType("datetime2");

                    b.Property<int>("status_order")
                        .HasColumnType("int");

                    b.Property<DateTime>("updatedtime")
                        .HasColumnType("datetime2");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("user_id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("_1015bookstore.web.Data.Entity.OrderDetail", b =>
                {
                    b.Property<int>("product_id")
                        .HasColumnType("int");

                    b.Property<int>("order_id")
                        .HasColumnType("int");

                    b.Property<float>("price")
                        .HasColumnType("real");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.HasKey("product_id", "order_id");

                    b.HasIndex("order_id");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("_1015bookstore.web.Data.Entity.Product", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("alias")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("buy_count")
                        .HasColumnType("int");

                    b.Property<int>("category_id")
                        .HasColumnType("int");

                    b.Property<string>("createdby")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("createdtime")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("flashsale")
                        .HasColumnType("bit");

                    b.Property<string>("image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("is_status")
                        .HasColumnType("int");

                    b.Property<int>("like_count")
                        .HasColumnType("int");

                    b.Property<string>("more_image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<float>("price")
                        .HasColumnType("real");

                    b.Property<int>("quanity")
                        .HasColumnType("int");

                    b.Property<int>("reviews")
                        .HasColumnType("int");

                    b.Property<float>("starts")
                        .HasColumnType("real");

                    b.Property<string>("updatedby")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("updatedtime")
                        .HasColumnType("datetime2");

                    b.Property<int>("view_count")
                        .HasColumnType("int");

                    b.Property<int>("waranty")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("category_id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("_1015bookstore.web.Data.Entity.ProductDetail", b =>
                {
                    b.Property<int>("product_id")
                        .HasColumnType("int");

                    b.Property<string>("author")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("brand")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("suppiler")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("product_id");

                    b.ToTable("ProductDetails");
                });

            modelBuilder.Entity("_1015bookstore.web.Data.Entity.PromotionalCode", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("alias")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("createdby")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("createdtime")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("discount_rate")
                        .HasColumnType("int");

                    b.Property<int>("is_status")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("updatedby")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("updatedtime")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("PromotionalCodes");
                });

            modelBuilder.Entity("_1015bookstore.web.Data.Entity.Review", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("contents")
                        .IsRequired()
                        .HasColumnType("ntext");

                    b.Property<DateTime>("createdtime")
                        .HasColumnType("datetime2");

                    b.Property<string>("deletedby")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("deletedtime")
                        .HasColumnType("datetime2");

                    b.Property<int>("is_status")
                        .HasColumnType("int");

                    b.Property<int>("product_id")
                        .HasColumnType("int");

                    b.Property<int>("starts")
                        .HasColumnType("int");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("product_id");

                    b.HasIndex("user_id");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("_1015bookstore.web.Data.Entity.TypedCategories_Promotionals", b =>
                {
                    b.Property<int>("category_id")
                        .HasColumnType("int");

                    b.Property<int>("promotional_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("expirationdate")
                        .HasColumnType("datetime2");

                    b.HasKey("category_id", "promotional_id");

                    b.HasIndex("promotional_id");

                    b.ToTable("TypedCategories_Promotionals");
                });

            modelBuilder.Entity("_1015bookstore.web.Data.Entity.TypedProducts_Promotionals", b =>
                {
                    b.Property<int>("product_id")
                        .HasColumnType("int");

                    b.Property<int>("promotional_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("expirationdate")
                        .HasColumnType("datetime2");

                    b.HasKey("product_id", "promotional_id");

                    b.HasIndex("promotional_id");

                    b.ToTable("TypedProducts_Promotionals");
                });

            modelBuilder.Entity("_1015bookstore.web.Data.Entity.TypedUsers_Promotionals", b =>
                {
                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.Property<int>("promotional_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("expirationdate")
                        .HasColumnType("datetime2");

                    b.HasKey("user_id", "promotional_id");

                    b.HasIndex("promotional_id");

                    b.ToTable("TypedUsers_Promotionals");
                });

            modelBuilder.Entity("_1015bookstore.web.Data.Entity.TypedUsers_UserTypes", b =>
                {
                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.Property<int>("usertype_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("expirationdate")
                        .HasColumnType("datetime2");

                    b.HasKey("user_id", "usertype_id");

                    b.HasIndex("usertype_id");

                    b.ToTable("TypedUsers_UserTypes");
                });

            modelBuilder.Entity("_1015bookstore.web.Data.Entity.TypedUserTypes_Promotionals", b =>
                {
                    b.Property<int>("usertype_id")
                        .HasColumnType("int");

                    b.Property<int>("promotional_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("expirationdate")
                        .HasColumnType("datetime2");

                    b.HasKey("usertype_id", "promotional_id");

                    b.HasIndex("promotional_id");

                    b.ToTable("TypedUserTypes_Promotionals");
                });

            modelBuilder.Entity("_1015bookstore.web.Data.Entity.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<DateTime>("createdtime")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("firstname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("is_status")
                        .HasColumnType("int");

                    b.Property<string>("lastname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("updatedtime")
                        .HasColumnType("datetime2");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("_1015bookstore.web.Data.Entity.UserAddress", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("address_detail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<float>("coordinates_X")
                        .HasColumnType("real");

                    b.Property<float>("coordinates_Y")
                        .HasColumnType("real");

                    b.Property<DateTime>("createdtime")
                        .HasColumnType("datetime2");

                    b.Property<string>("district")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("is_default")
                        .HasColumnType("bit");

                    b.Property<int>("is_status")
                        .HasColumnType("int");

                    b.Property<string>("receiver_name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("receiver_phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("sub_district")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("updatedtime")
                        .HasColumnType("datetime2");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("user_id");

                    b.ToTable("UserAddresses");
                });

            modelBuilder.Entity("_1015bookstore.web.Data.Entity.UserType", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("alias")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("createdby")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("createdtime")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("is_status")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("updatedby")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("updatedtime")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("UserTypes");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("_1015bookstore.web.Data.Entity.CartItem", b =>
                {
                    b.HasOne("_1015bookstore.web.Data.Entity.Product", "product")
                        .WithMany("cartitems")
                        .HasForeignKey("product_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CartItem_Product");

                    b.HasOne("_1015bookstore.web.Data.Entity.User", "user")
                        .WithMany("cartitems")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CartItem_User");

                    b.Navigation("product");

                    b.Navigation("user");
                });

            modelBuilder.Entity("_1015bookstore.web.Data.Entity.Order", b =>
                {
                    b.HasOne("_1015bookstore.web.Data.Entity.User", "user")
                        .WithMany("orders")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Order_User");

                    b.Navigation("user");
                });

            modelBuilder.Entity("_1015bookstore.web.Data.Entity.OrderDetail", b =>
                {
                    b.HasOne("_1015bookstore.web.Data.Entity.Order", "order")
                        .WithMany("orderdetails")
                        .HasForeignKey("order_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Orderdetail_Order");

                    b.HasOne("_1015bookstore.web.Data.Entity.Product", "product")
                        .WithMany("orderdetails")
                        .HasForeignKey("product_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Orderdetail_Product");

                    b.Navigation("order");

                    b.Navigation("product");
                });

            modelBuilder.Entity("_1015bookstore.web.Data.Entity.Product", b =>
                {
                    b.HasOne("_1015bookstore.web.Data.Entity.Category", "category")
                        .WithMany("products")
                        .HasForeignKey("category_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Product_Category");

                    b.Navigation("category");
                });

            modelBuilder.Entity("_1015bookstore.web.Data.Entity.ProductDetail", b =>
                {
                    b.HasOne("_1015bookstore.web.Data.Entity.Product", "product")
                        .WithOne("productdetail")
                        .HasForeignKey("_1015bookstore.web.Data.Entity.ProductDetail", "product_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("product");
                });

            modelBuilder.Entity("_1015bookstore.web.Data.Entity.Review", b =>
                {
                    b.HasOne("_1015bookstore.web.Data.Entity.Product", "product")
                        .WithMany("reviews_")
                        .HasForeignKey("product_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Review_Product");

                    b.HasOne("_1015bookstore.web.Data.Entity.User", "user")
                        .WithMany("reviews")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Review_User");

                    b.Navigation("product");

                    b.Navigation("user");
                });

            modelBuilder.Entity("_1015bookstore.web.Data.Entity.TypedCategories_Promotionals", b =>
                {
                    b.HasOne("_1015bookstore.web.Data.Entity.Category", "category")
                        .WithMany("typedcategories_promotionals")
                        .HasForeignKey("category_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TypeCategories_Promotionals_1");

                    b.HasOne("_1015bookstore.web.Data.Entity.PromotionalCode", "promotionalcodes")
                        .WithMany("typedcategories_promotionals")
                        .HasForeignKey("promotional_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TypeCategories_Promotionals_2");

                    b.Navigation("category");

                    b.Navigation("promotionalcodes");
                });

            modelBuilder.Entity("_1015bookstore.web.Data.Entity.TypedProducts_Promotionals", b =>
                {
                    b.HasOne("_1015bookstore.web.Data.Entity.Product", "product")
                        .WithMany("typedproducts_promotionals")
                        .HasForeignKey("product_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TypeProducts_Promotionals_1");

                    b.HasOne("_1015bookstore.web.Data.Entity.PromotionalCode", "promotionalcodes")
                        .WithMany("typedproducts_promotionals")
                        .HasForeignKey("promotional_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TypeProducts_Promotionals_2");

                    b.Navigation("product");

                    b.Navigation("promotionalcodes");
                });

            modelBuilder.Entity("_1015bookstore.web.Data.Entity.TypedUsers_Promotionals", b =>
                {
                    b.HasOne("_1015bookstore.web.Data.Entity.PromotionalCode", "promotionalcodes")
                        .WithMany("typedusers_promotionals")
                        .HasForeignKey("promotional_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TypeUsers_Promotionals_2");

                    b.HasOne("_1015bookstore.web.Data.Entity.User", "user")
                        .WithMany("typedusers_promotionals")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TypeUsers_Promotionals_1");

                    b.Navigation("promotionalcodes");

                    b.Navigation("user");
                });

            modelBuilder.Entity("_1015bookstore.web.Data.Entity.TypedUsers_UserTypes", b =>
                {
                    b.HasOne("_1015bookstore.web.Data.Entity.User", "user")
                        .WithMany("typedusers_usertypes")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TypeUsers_UserTypes_1");

                    b.HasOne("_1015bookstore.web.Data.Entity.UserType", "usertype")
                        .WithMany("typedusers_usertypes")
                        .HasForeignKey("usertype_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TypeUsers_UserTypes_2");

                    b.Navigation("user");

                    b.Navigation("usertype");
                });

            modelBuilder.Entity("_1015bookstore.web.Data.Entity.TypedUserTypes_Promotionals", b =>
                {
                    b.HasOne("_1015bookstore.web.Data.Entity.PromotionalCode", "promotionalcodes")
                        .WithMany("typedusertypes_promotionals")
                        .HasForeignKey("promotional_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TypeUserTypes_Promotionals_2");

                    b.HasOne("_1015bookstore.web.Data.Entity.UserType", "usertype")
                        .WithMany("typedusertypes_promotionals")
                        .HasForeignKey("usertype_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TypeUserTypes_Promotionals_1");

                    b.Navigation("promotionalcodes");

                    b.Navigation("usertype");
                });

            modelBuilder.Entity("_1015bookstore.web.Data.Entity.UserAddress", b =>
                {
                    b.HasOne("_1015bookstore.web.Data.Entity.User", "user")
                        .WithMany("useraddresses")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserAddress_User");

                    b.Navigation("user");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("_1015bookstore.web.Data.Entity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("_1015bookstore.web.Data.Entity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_1015bookstore.web.Data.Entity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("_1015bookstore.web.Data.Entity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("_1015bookstore.web.Data.Entity.Category", b =>
                {
                    b.Navigation("products");

                    b.Navigation("typedcategories_promotionals");
                });

            modelBuilder.Entity("_1015bookstore.web.Data.Entity.Order", b =>
                {
                    b.Navigation("orderdetails");
                });

            modelBuilder.Entity("_1015bookstore.web.Data.Entity.Product", b =>
                {
                    b.Navigation("cartitems");

                    b.Navigation("orderdetails");

                    b.Navigation("productdetail")
                        .IsRequired();

                    b.Navigation("reviews_");

                    b.Navigation("typedproducts_promotionals");
                });

            modelBuilder.Entity("_1015bookstore.web.Data.Entity.PromotionalCode", b =>
                {
                    b.Navigation("typedcategories_promotionals");

                    b.Navigation("typedproducts_promotionals");

                    b.Navigation("typedusers_promotionals");

                    b.Navigation("typedusertypes_promotionals");
                });

            modelBuilder.Entity("_1015bookstore.web.Data.Entity.User", b =>
                {
                    b.Navigation("cartitems");

                    b.Navigation("orders");

                    b.Navigation("reviews");

                    b.Navigation("typedusers_promotionals");

                    b.Navigation("typedusers_usertypes");

                    b.Navigation("useraddresses");
                });

            modelBuilder.Entity("_1015bookstore.web.Data.Entity.UserType", b =>
                {
                    b.Navigation("typedusers_usertypes");

                    b.Navigation("typedusertypes_promotionals");
                });
#pragma warning restore 612, 618
        }
    }
}
